"""empty message

Revision ID: 1457cbe2240a
Revises: 78fdb40c3bc2
Create Date: 2023-06-01 13:22:35.960577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1457cbe2240a'
down_revision = '78fdb40c3bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgName', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('visitLocation', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_column('visitLocation')
        batch_op.drop_column('imgName')

    # ### end Alembic commands ###
