"""empty message

Revision ID: 1f45ad17a9cc
Revises: 1457cbe2240a
Create Date: 2023-06-01 13:44:52.961593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1f45ad17a9cc'
down_revision = '1457cbe2240a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.alter_column('visitLocation',
               existing_type=sqlite.JSON(),
               type_=sa.PickleType(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.alter_column('visitLocation',
               existing_type=sa.PickleType(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
