"""empty message

Revision ID: 216688ae151e
Revises: 1f45ad17a9cc
Create Date: 2023-06-01 13:58:12.451690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216688ae151e'
down_revision = '1f45ad17a9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_column('visitLocation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitLocation', sa.BLOB(), nullable=True))

    op.drop_table('visit_location')
    # ### end Alembic commands ###
