"""empty message

Revision ID: 60217e388e40
Revises: 216688ae151e
Create Date: 2023-06-02 18:19:56.511364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60217e388e40'
down_revision = '216688ae151e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.alter_column('shortUrl',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.alter_column('shortUrl',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
